language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip 
  - pip install -U pytest
  - pip install pandas
  - pip install codecov
script: 
  - pytest tests
after_success:
  - codecov 
