language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip 
  - pip install -U pytest
  - pip install pandas
  - pip install codecov
  - pip install pytest-cov
script: 
  - pytest tests
  - pytest --cov=./ --cov-report=xml
after_success:
  - codecov 
