language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip 
  - pip install -U pytest
  - pip install pandas
  - pip install pytest-cov
  - pip install coveralls
script: 
  - coverage run --source=Project_Euler/ -m pytest tests/
after_success:
  - coveralls --verbose
