'''
Problem 29

Consider all integer combinations of a**b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

If they are then placed in numerical order, with any repeats removed, 
we get the following sequence of 15 distinct terms:

    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 
and 2 ≤ b ≤ 100?

Ans: 5374
'''
import numpy as np


def findCombos(bases: np.array, powers: np.array) -> set:
    '''
    Parameters
    ----------
    bases : np.array
        The array of bases to consider.
    powers : np.array
        The array of powers to raise the bases to.
    Returns
    -------
    set
        Set of distinct terms with bases a and powers b corresponding
        to the equation a**b.
    '''
    combos = set([])
    for i in bases:
        combos.update(np.power(i, powers))
    return combos


if __name__ == "__main__":
    print(len(findCombos(np.arange(2,100+1), np.arange(2,100+1))))